name = "DebugPrinting"
uuid = "8c5098b9-70d2-472f-b7bd-7e1230aee38c"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "1.0.0"

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
